---
# This vars file corresponds to the HQ_NYC IDF stack (hq_nyc-sw02.hq_nyc_internal_domain.com.yml),
# located on the Second floor of the HQ building.
# version 2.1 - Written by Alfredo Jo Â® - 2024

uplinks:
  - port: TenGigabitEthernet1/1/1
    name: core01
    vlan: 'trunk'

  - port: TenGigabitEthernet3/1/1
    name: core01
    vlan: 'trunk'

interfaces:
  - port: GigabitEthernet1/0/1
    name: AV-01
    vlan: '40'

  - port: GigabitEthernet1/0/2
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/3
    name: GUEST-01
    vlan: '200'

  - port: GigabitEthernet1/0/4
    name: AV-02
    vlan: '40'

  - port: GigabitEthernet1/0/5
    name: SEC-CAM-01
    vlan: '30'

  - port: GigabitEthernet1/0/6
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/7
    name: SEC-CAM-02
    vlan: '30'

  - port: GigabitEthernet1/0/8
    name: SEC-CAM-03
    vlan: '30'

  - port: GigabitEthernet1/0/9
    name: GUEST-02
    vlan: '200'

  - port: GigabitEthernet1/0/10
    name: AV-03
    vlan: '40'

  - port: GigabitEthernet1/0/11
    name: GUEST-03
    vlan: '200'

  - port: GigabitEthernet1/0/12
    name: SEC-CAM-04
    vlan: '30'

  - port: GigabitEthernet1/0/13
    name: SEC-CAM-05
    vlan: '30'

  - port: GigabitEthernet1/0/14
    name: AV-04
    vlan: '40'

  - port: GigabitEthernet1/0/15
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/16
    name: INT-01
    vlan: '10'

  - port: GigabitEthernet1/0/17
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/18
    name: SEC-CAM-06
    vlan: '30'

  - port: GigabitEthernet1/0/19
    name: SEC-CAM-07
    vlan: '30'

  - port: GigabitEthernet1/0/20
    name: AV-05
    vlan: '40'

  - port: GigabitEthernet1/0/21
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/22
    name: INT-02
    vlan: '10'

  - port: GigabitEthernet1/0/23
    name: SEC-CAM-08
    vlan: '30'

  - port: GigabitEthernet1/0/24
    name: GUEST-04
    vlan: '200'

  - port: GigabitEthernet1/0/25
    name: INT-03
    vlan: '10'

  - port: GigabitEthernet1/0/26
    name: GUEST-05
    vlan: '200'

  - port: GigabitEthernet1/0/27
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/28
    name: GUEST-06
    vlan: '200'

  - port: GigabitEthernet1/0/29
    name: GUEST-07
    vlan: '200'

  - port: GigabitEthernet1/0/30
    name: INT-04
    vlan: '10'

  - port: GigabitEthernet1/0/31
    name: GUEST-08
    vlan: '200'

  - port: GigabitEthernet1/0/32
    name: GUEST-09
    vlan: '200'

  - port: GigabitEthernet1/0/33
    name: AV-06
    vlan: '40'

  - port: GigabitEthernet1/0/34
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/35
    name: SEC-CAM-09
    vlan: '30'

  - port: GigabitEthernet1/0/36
    name: INT-05
    vlan: '10'

  - port: GigabitEthernet1/0/37
    name: SEC-CAM-10
    vlan: '30'

  - port: GigabitEthernet1/0/38
    name: SEC-CAM-11
    vlan: '30'

  - port: GigabitEthernet1/0/39
    name: SEC-CAM-12
    vlan: '30'

  - port: GigabitEthernet1/0/40
    name: SEC-CAM-13
    vlan: '30'

  - port: GigabitEthernet1/0/41
    name: GUEST-10
    vlan: '200'

  - port: GigabitEthernet1/0/42
    name: GUEST-11
    vlan: '200'

  - port: GigabitEthernet1/0/43
    name: AV-07
    vlan: '40'

  - port: GigabitEthernet1/0/44
    name: GUEST-12
    vlan: '200'

  - port: GigabitEthernet1/0/45
    name: INT-06
    vlan: '10'

  - port: GigabitEthernet1/0/46
    name: none
    vlan: '1'

  - port: GigabitEthernet1/0/47
    name: INT-07
    vlan: '10'

  - port: GigabitEthernet1/0/48
    name: GUEST-13
    vlan: '200'

  - port: GigabitEthernet2/0/1
    name: INT-08
    vlan: '10'

  - port: GigabitEthernet2/0/2
    name: none
    vlan: '1'

  - port: GigabitEthernet2/0/3
    name: INT-09
    vlan: '10'

  - port: GigabitEthernet2/0/4
    name: AV-08
    vlan: '40'

  - port: GigabitEthernet2/0/5
    name: AV-09
    vlan: '40'

  - port: GigabitEthernet2/0/6
    name: GUEST-14
    vlan: '200'

  - port: GigabitEthernet2/0/7
    name: GUEST-15
    vlan: '200'

  - port: GigabitEthernet2/0/8
    name: INT-10
    vlan: '10'

  - port: GigabitEthernet2/0/9
    name: none
    vlan: '1'

  - port: GigabitEthernet2/0/10
    name: GUEST-16
    vlan: '200'

  - port: GigabitEthernet2/0/11
    name: AV-10
    vlan: '40'

  - port: GigabitEthernet2/0/12
    name: INT-11
    vlan: '10'

  - port: GigabitEthernet2/0/13
    name: SEC-CAM-14
    vlan: '30'

  - port: GigabitEthernet2/0/14
    name: SEC-CAM-15
    vlan: '30'

  - port: GigabitEthernet2/0/15
    name: GUEST-17
    vlan: '200'

  - port: GigabitEthernet2/0/16
    name: INT-12
    vlan: '10'

  - port: GigabitEthernet2/0/17
    name: INT-13
    vlan: '10'

  - port: GigabitEthernet2/0/18
    name: INT-14
    vlan: '10'

  - port: GigabitEthernet2/0/19
    name: INT-15
    vlan: '10'

  - port: GigabitEthernet2/0/20
    name: none
    vlan: '1'

  - port: GigabitEthernet2/0/21
    name: GUEST-18
    vlan: '200'

  - port: GigabitEthernet2/0/22
    name: AV-11
    vlan: '40'

  - port: GigabitEthernet2/0/23
    name: GUEST-19
    vlan: '200'

  - port: GigabitEthernet2/0/24
    name: SEC-CAM-16
    vlan: '30'

  - port: GigabitEthernet2/0/25
    name: GUEST-20
    vlan: '200'

  - port: GigabitEthernet2/0/26
    name: none
    vlan: '1'

  - port: GigabitEthernet2/0/27
    name: GUEST-21
    vlan: '200'

  - port: GigabitEthernet2/0/28
    name: GUEST-22
    vlan: '200'

  - port: GigabitEthernet2/0/29
    name: SEC-CAM-17
    vlan: '30'

  - port: GigabitEthernet2/0/30
    name: GUEST-23
    vlan: '200'

  - port: GigabitEthernet2/0/31
    name: SEC-CAM-18
    vlan: '30'

  - port: GigabitEthernet2/0/32
    name: INT-16
    vlan: '10'

  - port: GigabitEthernet2/0/33
    name: GUEST-24
    vlan: '200'

  - port: GigabitEthernet2/0/34
    name: none
    vlan: '1'

  - port: GigabitEthernet2/0/35
    name: INT-17
    vlan: '10'

  - port: GigabitEthernet2/0/36
    name: SEC-CAM-19
    vlan: '30'

  - port: GigabitEthernet2/0/37
    name: AV-12
    vlan: '40'

  - port: GigabitEthernet2/0/38
    name: SEC-CAM-20
    vlan: '30'

  - port: GigabitEthernet2/0/39
    name: SEC-CAM-21
    vlan: '30'

  - port: GigabitEthernet2/0/40
    name: AV-13
    vlan: '40'

  - port: GigabitEthernet2/0/41
    name: none
    vlan: '1'

  - port: GigabitEthernet2/0/42
    name: INT-18
    vlan: '10'

  - port: GigabitEthernet2/0/43
    name: GUEST-25
    vlan: '200'

  - port: GigabitEthernet2/0/44
    name: INT-19
    vlan: '10'

  - port: GigabitEthernet2/0/45
    name: SEC-CAM-22
    vlan: '30'

  - port: GigabitEthernet2/0/46
    name: AV-14
    vlan: '40'

  - port: GigabitEthernet2/0/47
    name: GUEST-26
    vlan: '200'

  - port: GigabitEthernet2/0/48
    name: INT-20
    vlan: '10'

  - port: GigabitEthernet3/0/1
    name: INT-21
    vlan: '10'

  - port: GigabitEthernet3/0/2
    name: SEC-CAM-23
    vlan: '30'

  - port: GigabitEthernet3/0/3
    name: AV-15
    vlan: '40'

  - port: GigabitEthernet3/0/4
    name: AV-16
    vlan: '40'

  - port: GigabitEthernet3/0/5
    name: INT-22
    vlan: '10'

  - port: GigabitEthernet3/0/6
    name: AV-17
    vlan: '40'

  - port: GigabitEthernet3/0/7
    name: INT-23
    vlan: '10'

  - port: GigabitEthernet3/0/8
    name: INT-24
    vlan: '10'

  - port: GigabitEthernet3/0/9
    name: GUEST-27
    vlan: '200'

  - port: GigabitEthernet3/0/10
    name: GUEST-28
    vlan: '200'

  - port: GigabitEthernet3/0/11
    name: INT-25
    vlan: '10'

  - port: GigabitEthernet3/0/12
    name: INT-26
    vlan: '10'

  - port: GigabitEthernet3/0/13
    name: GUEST-29
    vlan: '200'

  - port: GigabitEthernet3/0/14
    name: AV-18
    vlan: '40'

  - port: GigabitEthernet3/0/15
    name: AV-19
    vlan: '40'

  - port: GigabitEthernet3/0/16
    name: none
    vlan: '1'

  - port: GigabitEthernet3/0/17
    name: INT-27
    vlan: '10'

  - port: GigabitEthernet3/0/18
    name: GUEST-30
    vlan: '200'

  - port: GigabitEthernet3/0/19
    name: GUEST-31
    vlan: '200'

  - port: GigabitEthernet3/0/20
    name: INT-28
    vlan: '10'

  - port: GigabitEthernet3/0/21
    name: GUEST-32
    vlan: '200'

  - port: GigabitEthernet3/0/22
    name: GUEST-33
    vlan: '200'

  - port: GigabitEthernet3/0/23
    name: none
    vlan: '1'

  - port: GigabitEthernet3/0/24
    name: SEC-CAM-24
    vlan: '30'

  - port: GigabitEthernet3/0/25
    name: none
    vlan: '1'

  - port: GigabitEthernet3/0/26
    name: none
    vlan: '1'

  - port: GigabitEthernet3/0/27
    name: AV-20
    vlan: '40'

  - port: GigabitEthernet3/0/28
    name: SEC-CAM-25
    vlan: '30'

  - port: GigabitEthernet3/0/29
    name: GUEST-34
    vlan: '200'

  - port: GigabitEthernet3/0/30
    name: SEC-CAM-26
    vlan: '30'

  - port: GigabitEthernet3/0/31
    name: GUEST-35
    vlan: '200'

  - port: GigabitEthernet3/0/32
    name: AV-21
    vlan: '40'

  - port: GigabitEthernet3/0/33
    name: none
    vlan: '1'

  - port: GigabitEthernet3/0/34
    name: none
    vlan: '1'

  - port: GigabitEthernet3/0/35
    name: AV-22
    vlan: '40'

  - port: GigabitEthernet3/0/36
    name: AV-23
    vlan: '40'

  - port: GigabitEthernet3/0/37
    name: INT-29
    vlan: '10'

  - port: GigabitEthernet3/0/38
    name: INT-30
    vlan: '10'

  - port: GigabitEthernet3/0/39
    name: INT-31
    vlan: '10'

  - port: GigabitEthernet3/0/40
    name: GUEST-36
    vlan: '200'

  - port: GigabitEthernet3/0/41
    name: INT-32
    vlan: '10'

  - port: GigabitEthernet3/0/42
    name: INT-33
    vlan: '10'

  - port: GigabitEthernet3/0/43
    name: INT-34
    vlan: '10'

  - port: GigabitEthernet3/0/44
    name: AV-24
    vlan: '40'

  - port: GigabitEthernet3/0/45
    name: SEC-CAM-27
    vlan: '30'

  - port: GigabitEthernet3/0/46
    name: SEC-CAM-28
    vlan: '30'

  - port: GigabitEthernet3/0/47
    name: INT-35
    vlan: '10'

  - port: GigabitEthernet3/0/48
    name: INT-36
    vlan: '10'
